language: python
services:
  - redis-server

python:
  - "3.4"
  - "3.5"
  - "nightly"

install:
  - pip install -r requirements.txt

before_script:
  ###### We need Redis >= 3.0.2 in order to use ZADD ... NX ######
  - wget http://download.redis.io/releases/redis-stable.tar.gz
  - tar xzf redis-stable.tar.gz
  - cd redis-stable
  - make
  - echo 'daemonize yes' | src/redis-server -
  - cd ..
  ################################################################

script:
  - py.test tests.py
