language: python

python:
  - "3.4"
  - "3.5"
  - "nightly"

install:
  - pip install -r requirements.txt

addons:
  apt:
    packages:
      - redis-server
      
before_script:
  - redis-server --daemonize yes

script:
  - py.test tests.py
